apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding
  namespace: react-ns
subjects:
  - kind: ServiceAccount
    name: reactappdemo
    namespace: react-ns
roleRef:
  kind: Role
  name: reactapp-role
  apiGroup: rbac.authorization.k8s.io